version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development

  db:
    image: sqlite
    volumes:
      - ./tor_list.db:/var/lib/sqlite/tor_list.db