version: '3'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - tor_list_data:/app/tor_list_data
    environment:
      - FLASK_ENV=development

volumes:
  tor_list_data:
